spring.application.name=demo-spring-security-inRAMStorage
app.end-point = /api

#configuration username password with spring security
spring.security.user.name =phanith
spring.security.user.password =nith@123