spring.application.name=spring-security-database

#config database connection in mysql
spring.datasource.url = jdbc:mysql://localhost:3306/spring_boot_spring_security
spring.datasource.username = root
spring.datasource.password =
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver
spring.jpa.show.sql = true
spring.jpa.hibernate.ddl-auto = update


